import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import { ThemeProvider } from "next-themes";

import { PROJECTS } from "@/data/projects";

import "@/styles/globals.css";
import "@/views/HomeView/HomeView.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface BaseLayoutProps {
  children: React.ReactNode;
  footer: React.ReactNode;
  header?: React.ReactNode;
}

export default function BaseLayout(props: BaseLayoutProps) {
  const { children, footer, header = <></> } = props;

  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        {/* Add preload links for all project images */}
        {PROJECTS.map((project) => (
          <link
            key={project.imageUrl}
            rel="preload"
            as="image"
            href={project.imageUrl}
          />
        ))}
      </Head>
      <body
        className={[
          geistSans.variable,
          geistMono.variable,
          "antialiased",
          "bg-primary dark:bg-primary-dark",
          "text-on-primary dark:text-on-primary-dark",
        ]
          .join(" ")
          .trim()}
      >
        <ThemeProvider attribute="class">
          {header}
          <main>{children}</main>
          {footer}
        </ThemeProvider>
      </body>
    </html>
  );
}
